[package]
name = "rowifi_models"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
twilight-model = { branch = "main", git = "https://github.com/twilight-rs/twilight" }
serde = { version = "1.0" }