[package]
name = "rowifi_models"
version = "4.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = { version = "1.5" }
tokio-postgres = { version = "0.7", features = ["with-serde_json-1"] }
twilight-model = { branch = "main", git = "https://github.com/twilight-rs/twilight" }
serde = { version = "1.0" }
serde_repr = { version = "0.1" }