[package]
name = "rowifi_framework"
version = "4.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rowifi_cache = { path = "../rowifi_cache" }
rowifi_models = { path = "../rowifi_models" }
twilight-http = { branch = "main", git = "https://github.com/twilight-rs/twilight", default-features = false, features = ["rustls-webpki-roots"] }