[package]
name = "rowifi_database"
version = "4.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deadpool-postgres = { version = "0.14" }
tokio-postgres = { version = "0.7" }
tracing = { workspace = true }