name: Lints

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: ""

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Install fontconfig
        run: sudo apt-get update && sudo apt-get install -y fontconfig

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Cache cargo dependencies
        uses: actions/cache@v2
        with:
          path: target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run cargo clippy
        run: cargo clippy --all-targets -- -D warnings
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

  rustfmt:
    name: Format
    runs-on: ubuntu-latest

    steps:
      - name: Set github credentials
        run: |
          /usr/bin/git config --global --add url."https://${{ secrets.GH_PAT }}:x-oauth-basic@github".insteadOf ssh://git@github
          /usr/bin/git config --global --add url."https://${{ secrets.GH_PAT }}:x-oauth-basic@github".insteadOf https://github
          /usr/bin/git config --global --add url."https://${{ secrets.GH_PAT }}:x-oauth-basic@github".insteadOf git@github

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install nightly toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          components: rustfmt
          toolchain: nightly

      - name: Run cargo fmt
        run: cargo fmt --all -- --check
