name: Lints

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: ""

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Run clippy
        run: cargo clippy --all-features --all-targets
        
  rustfmt:
    name: Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      
      - name: Install nightly toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          components: rustfmt
          toolchain: nightly

      - name: Run cargo fmt
        run: cargo fmt --all -- --check